application: todolist-app
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: main.py
